language: go

go:
  - 1.8
  - 1.9

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls

script:
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  - $GOPATH/bin/goveralls -service=travis-ci -v -package ./pkg/...

