language: go

go:
  - 1.8
  - 1.9

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  # Install dependencies using glide
  - glide install
  # We need to remove the vendored dependencies of apiextensions otherwise we get type conflicts.
  - rm -rf vendor/k8s.io/apiextensions-apiserver/vendor

script:
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  - $GOPATH/bin/goveralls -service=travis-ci -v -package ./pkg/...

