# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v1
    params:
      tfJobVersion: v1alpha1
  - app_dir: kubeflow/tf-operator/test/workflows
    component: workflows
    name: v2
    params:
      tfJobVersion: v1alpha2