kind: Service
apiVersion: v1
metadata:
  name: airflow
spec:
  selector:
    name: airflow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: airflow
    spec:
      containers:
      - name: airflow
        image: puckel/docker-airflow              
        # What arguments do we need to set to use the LocalExecutor
        env:
        - name: EXECUTOR
          value: Local
        - name: LOAD_EX
          value: "n"
        - name: POSTGRES_HOST
          value: localhost
        ports:
        - containerPort: 8080
        # TODO(jlewi): Should we store the postgres data on a PD to make it
        # invariant to disruptions.
        # TODO(jlewi): We should probably change this to an image
        # we build so we can build the DAGS into the image.
      - name: postgres
        # TODO(jlewi): We should probably change this to an image
        # we build so we can build the DAGS into the image.
        image: postgres:9.6
        env:
        - name: POSTGRES_USER
          value: airflow
        - name: POSTGRES_PASSWORD
          value: airflow
        - name: POSTGRES_DB
          value: airflow
        ports:
        - containerPort: 5432
