# permissions for end users to view xgboostjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xgboostjob-viewer-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - xgboostjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - xgboostjobs/status
  verbs:
  - get
