apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
commonLabels:
  app: tf-job-operator
  kustomize.component: tf-job-operator
  app.kubernetes.io/component: tfjob
  app.kubernetes.io/name: tf-job-operator
images:
- name: 809251082950.dkr.ecr.us-west-2.amazonaws.com/tf-operator
  newTag: "0.1"
