apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator
    newName: kubeflow/training-operator
    newTag: "46c586463e3c13b0d4f2d534aae84a46329dc4ef"
