apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - ../../manager
  - kubeflow-training-roles.yaml
images:
  - name: kubeflow/training-operator:v1.0.0
    newName: deepakmuley/kubeflow-training-operator
    newTag: "1"
