apiVersion: kubeflow.org/v1
kind: GenericJob
metadata:
  name: generic-job-test
spec:
  replicaSpecs:
    PS:
      replicas: 2
      template:
        spec:
          containers:
            - name: kubeflow
              image: nginx:perl
              ports:
              - containerPort: 443
    Worker:
      replicas: 3
      template:
        spec:
          containers:
            - name: kubeflow
              image: nginx:perl
              ports:
              - containerPort: 80
