apiVersion: kubeflow.org/v1
kind: GenericJob
metadata:
  name: generic-job-test
spec:
  replicaSpecs:
    PS:
      replicas: 2
      template:
        spec:
          containers:
            - name: ps
              image: nginx:perl
    Worker:
      replicas: 3
      template:
        spec:
          containers:
            - name: worker
              image: nginx:perl
