apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: tfjob-simple
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: tensorflow
# Source for the image is located here: https://github.com/kubeflow/katib/tree/master/examples/v1beta1/trial-images/tf-mnist-with-summaries
              image: docker.io/kubeflowkatib/tf-mnist-with-summaries:latest
              command:
              - "python"
              - "/opt/tf-mnist-with-summaries/mnist.py"
              - "--epochs=1"
