# Docker image to use.
image: gcr.io/cloud-ml-dev/tf_operator:v20171105-ed68e4f-dirty-ce2b348
test_image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff

# Which cloud provider is kubernetes hosted on.
# Supported values are gke or azure.
# If no value is provided, you will have to supply your own configuration, see README.
cloud:

## Install Default RBAC roles and bindings
rbac:
  install: false
  apiVersion: v1beta1
