# Docker image to use.
image: gcr.io/mlkube-testing/tf_operator:v20171109-fa4c8bb-dirty-3ff3e48
test_image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff

# Which cloud provider is kubernetes hosted on.
# Supported values are gke or azure.
# If no value is provided, you will have to supply your own configuration, see README.
cloud:

## Install Default RBAC roles and bindings
rbac:
  install: false
  apiVersion: v1beta1
