name: Python Test

on:
  - push
  - pull_request

jobs:
  python-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

        # TODO (andreyvelich): We need to replace this action with script to do
        # linting and formatting for Training Operator SDK.
      - name: Check Python code with Black
        uses: psf/black@stable
        with:
          version: 23.9.1
          options: --check --exclude '/*kubeflow_org_v1*|__init__.py|api_client.py|configuration.py|exceptions.py|rest.py'
          src: sdk/

      - name: Install dependencies
        run: |
          pip install flake8 pytest python-dateutil urllib3 kubernetes
          pip install -U './sdk/python[huggingface]'

      - name: Run unit test for training sdk
        run: pytest ./sdk/python/kubeflow/training/api/training_client_test.py

      - name: Lint with flake8
        run: |
          flake8 sdk/ --count --select=E9,F63,F7,F82 --extend-ignore=W503 --exclude=/*kubeflow_org_v1*,__init__.py,api_client.py,configuration.py,exceptions.py,rest.py --show-source --statistics
          flake8 sdk/ --count --extend-ignore=W503 --exclude=/*kubeflow_org_v1*,__init__.py,api_client.py,configuration.py,exceptions.py,rest.py --max-complexity=10 --max-line-length=100 --statistics
