name: Go Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}/go
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["1.21.12", "1.22.9", "1.23.6"]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2

      - name: Run Go test
        run: make test KUBERNETES_VERSION=${{ matrix.kubernetes-version }}

      - name: Coveralls report
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
          working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/training-operator
